split_sentences: fix parenthesis, more rules, tests
OSS-Pole-Emploi/words_n_fun pull request #33
Opened 2024-04-09 15:11 UTC by dgarlor

## ✒️ Context

Method split_sentences had a bug with parenthesis and some regexes could be improved. 

- What kind of change does this PR introduce ?

  - [x] Bugfix
  - [x] Feature
  - [x] Refactoring
  - [ ] Other, please describe:

## 🧱 Description of Changes

- Refactor code about extracting parenthesis, and regexes
- Fix bug with perenthesis
- Improve regex with special cases (acronyms, M. Mme. ...)
- Increase tests with more specific test cases

## 🩺 Testing

- _Add bullet points summarizing your changes here_

  - [ ] This change does not need new tests
  - [x] Added/Updated unit tests

## 🔗 References

_Does this depend on other work, documents, or tickets?_

- **Issue**: Closes #XXXX

---

**Contribution License Agreement**

By submitting this pull request you agree that all contributions to this project are made under the GNU AFFERO GENERAL PUBLIC LICENSE.

2024-04-19 15:00 UTC, gsolard requested changes
Adress the comment and everything should be good to go

2024-05-07 07:15 UTC, dgarlor commented on words_n_fun/preprocessing/split_sentences.py
> +    assert version in [1,2], " Vsplit_sentences version must be 1 or 2"
replace by a exception

2024-05-07 07:15 UTC, dgarlor commented on tests/test_8_split_sentences.py
> +        self.assertEqual(split_sentences.split_sentences(text,2), result)
i run ruff to format the 2 files completely

2024-05-07 07:22 UTC, gsolard approved these changes

2024-05-07 07:23 UTC, merged